services:
  imagegenerator.api:
    image: ${DOCKER_REGISTRY-}imagegeneratorapi
    container_name: imagegenerator.api
    build:
      context: .
      dockerfile: ImageGenerator.Api/Dockerfile
    ports:
     - "5000:5000"
     - "5001:5001"

  imagegenerator.database:
     image: postgres:latest
     container_name: imagegenerator.database
     environment:
       - POSTGRES_DB=imagegenerator
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=pddzusslQj
     volumes:
      - ./.containers/imagegenerator-db:/var/lib/postgresqlnew/data
     ports:
      - 5432:5432
