services:
  imagegenerator.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - ASPNETCORE_URLS= http://0.0.0.0:5000;https://0.0.0.0:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path= /app/certificates/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password= Test1234      

    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro