services:
  imagegenerator.api:
    depends_on:
      imagegenerator.database:
        condition: service_healthy
    image: ${DOCKER_REGISTRY-}imagegeneratorapi
    container_name: imagegenerator.api
    build:
      context: .
      dockerfile: ImageGenerator.Api/Dockerfile
    ports:
     - "5000:5000"
     - "5001:5001"

  imagegenerator.database:
     image: postgres:latest
     container_name: imagegenerator.database
     environment:
       - POSTGRES_DB=imagegenerator
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=pddzusslQj
     volumes:
      - ./.containers/imagegenerator-db:/var/lib/postgresql/data
     ports:
      - 5432:5432
     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres"]
       interval: 10s
       timeout: 5s
       retries: 5
